title: "Templates/Six Columns Layout"
description:
  component: "Six column layout component."
## Canvas height
height: 200
## row settings
row:
  description: boolean
  default: false
  table:
    category: fields
## Column settings
container:
  description: boolean
  default: false
  table:
    category: fields
## Column 1 content settings.
column_1_content:
  description: string
  default: 'string'
  table:
    category: fields
## Column 2 content settings.
column_2_content:
  description: string
  default: 'string'
  table:
    category: fields
## Column 3 content settings.
column_3_content:
  description: string
  default: 'string'
  table:
    category: fields
## Column 4 content settings.
column_4_content:
  description: string
  default: 'string'
  table:
    category: fields
## Column 5 content settings.
column_5_content:
  description: string
  default: 'string'
  table:
    category: fields
## Column 6 content settings.
column_6_content:
  description: string
  default: 'string'
  table:
    category: fields
## Column 1 size
column_1:
  description: Bootstrap column class
  table:
    category: settings
  default: 'col-2'
  options:
    '16.66%': 'col-2'
    '25%': 'col-3'
    '33%': 'col-4'
    '50%': 'col-6'
## Column 2 size
column_2:
  description: Bootstrap column class
  table:
    category: settings
  default: 'col-2'
  options:
    '16.66%': 'col-2'
    '25%': 'col-3'
    '33%': 'col-4'
    '50%': 'col-6'
## Column 3 size
column_3:
  description: Bootstrap column class
  table:
    category: settings
  default: 'col-2'
  options:
    '16.66%': 'col-2'
    '25%': 'col-3'
    '33%': 'col-4'
    '50%': 'col-6'
## Column 4 size
column_4:
  description: Bootstrap column class
  table:
    category: settings
  default: 'col-2'
  options:
    '16.66%': 'col-2'
    '25%': 'col-3'
    '33%': 'col-4'
    '50%': 'col-6'
## Column 5 size
column_5:
  description: Bootstrap column class
  table:
    category: settings
  default: 'col-2'
  options:
    '16.66%': 'col-2'
    '25%': 'col-3'
    '33%': 'col-4'
    '50%': 'col-6'
## Column 6 size
column_6:
  description: Bootstrap column class
  table:
    category: settings
  default: 'col-2'
  options:
    '16.66%': 'col-2'
    '25%': 'col-3'
    '33%': 'col-4'
    '50%': 'col-6'
