title: "Atoms/Alert"
description:
  component: "Provide contextual feedback messages for typical user actions with the handful of available and flexible alert messages."
## Canvas height
height: 150
## Background Color settings
color:
  options:
    Primary: primary
    Secondary: secondary
    Success: success
    Danger: danger
    warning: warning
    Info: info
    Light: light
    Dark: dark
  default: primary
  description: Bootstrap class
  table:
    category: settings
## Heading tag settings
heading:
  description: string
  default: string
  table:
    category: fields
## Content settings
content:
  description: string
  default: string
  table:
    category: fields
## Dismissable button settings
dismissible:
  description: boolean
  default: true
  table:
    category: fields
