title: "Templates/Two Columns Layout"
description:
  component: "Two column layout component."
## Canvas height
height: 350
## row settings
row:
  description: boolean
  default: false
  table:
    category: fields
## Column settings
container:
  description: boolean
  default: false
  table:
    category: fields
## Column 1 content settings.
column_1_content:
  description: string
  default: "string"
  table:
    category: fields
## Column 2 content settings.
column_2_content:
  description: string
  default: "string"
  table:
    category: fields
desktop_columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-6"
  options:
    "25% - 75%": "25_75"
    "33% - 67%": "33_67"
    "50% - 50%": "50_50"
    "67% - 33%": "67_33"
    "75% - 25%": "75_25"
tablet_columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-6"
  options:
    "25% - 75%": "25_75"
    "33% - 67%": "33_67"
    "50% - 50%": "50_50"
    "67% - 33%": "67_33"
    "75% - 25%": "75_25"
    "100% - 100%": "100_100"
mobile_columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-12"
  options:
    "100% - 100%": "100_100"
