title: "Atoms/CloseButton"
description:
  component: "A generic close button for dismissing content like modals and alerts."
## Canvas height
height: 150
## Outline button settings
outline:
  description: boolean
  default: false
  table:
    category: settings
## Size settings
size:
  description: Bootstrap class
  table:
    category: settings
  default: ''
  options:
    Default: ''
    Small: btn-sm
    Mediam: btn-md
    Large: btn-lg
