title: "Templates/Four Columns Layout"
description:
  component: "three column layout component."
## Canvas height
height: 350
## row settings
row:
  description: boolean
  default: false
  table:
    category: fields
## Column settings
container:
  description: boolean
  default: false
  table:
    category: fields
## Column 1 content settings.
column_1_content:
  description: string
  default: "string"
  table:
    category: fields
## Column 2 content settings.
column_2_content:
  description: string
  default: "string"
  table:
    category: fields
## Column 3 content settings.
column_3_content:
  description: string
  default: "string"
  table:
    category: fields
## Column 3 content settings.
column_4_content:
  description: string
  default: "string"
  table:
    category: fields
## Columns size settings.
columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-6"
  options:
    "25% - 25% - 25% - 25%": "25_25_25_25"
    "50% - 50% - 50% - 50%": "50_50_50_50"
